//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronosBeta.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateTimer
    {
        public int ID_DateTimer { get; set; }
        public int Users { get; set; }
        public System.DateTime Day { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public System.TimeSpan TimeEnd { get; set; }
        public string AllRunProgram { get; set; }
    
        public virtual Users Users1 { get; set; }
    }
}
