//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronosBeta.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screenshot
    {
        public int Id_Screenshot { get; set; }
        public byte[] ImageScreenshot { get; set; }
        public System.TimeSpan Time { get; set; }
        public int DateTimer { get; set; }
    
        public virtual DateTimer DateTimer1 { get; set; }
    }
}
