//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronosBeta.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskTimer = new HashSet<TaskTimer>();
        }
    
        public int ID_Task { get; set; }
        public string NameTask { get; set; }
        public int Project { get; set; }
        public int UserCreateTask { get; set; }
        public int UserDoTask { get; set; }
        public bool ItsOver { get; set; }
        public double EstimatedTime { get; set; }
        public Nullable<double> AllSpentTime { get; set; }
        public string Description { get; set; }
        public System.DateTime Deadline { get; set; }
    
        public virtual Project Project1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTimer> TaskTimer { get; set; }
    }
}
