//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronosBeta.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTimer
    {
        public int ID_TaskTimer { get; set; }
        public int Users { get; set; }
        public int Task { get; set; }
        public double SpentTime { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
    
        public virtual Task Task1 { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
