//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronosBeta.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerProject
    {
        public int ID_TimerProject { get; set; }
        public int Users { get; set; }
        public int Project { get; set; }
        public System.TimeSpan SpentTime { get; set; }
        public string Description { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
